rules: ['setup_data', 'pull_genotypes', 'copy_par', 'renumf90', 'airemlf90', 'cleanup']

r_module: "r/r-3.6.2-python-2.7.14-tk"

mpi_module: "openmpi/openmpi-3.1.3-intel-16.0.2"

renumf90_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/mizzou_hairshed/source_functions/renumf90"

aireml_path: "/storage/hpc/group/UMAG/WORKING/hjdzpd/mizzou_hairshed/source_functions/airemlf90"

geno_prefix: "data/raw_data/geno_dump/200924_HairShed.850K"

# model: ['fixed9', 'an1', 'bg1', 'igs1', 'fixed14', 'fixed15']

model: ['fixed14', 'fixed15']

hair_col: {'fixed9':['3'], 'an1':['3'], 'bg1':['3'], 'igs1':['3'], 'fixed14':['3'], 'fixed15':['5']}

pct_excl: "0.25"

iter: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
