rules: ['pop_labels', 'recode_input', 'create_par', 'smartpca']

plink_module: "plink/plink-1.90b"

plink_nt: 12

r_module: "r/r-4.0.0-gcc-10.1.0"

eigensoft_module: "eigensoft/eigensoft-7.2.1"

chr: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29']

geno_prefix: "data/raw_data/geno_dump/200924_HairShed.850K"
