rules: ['setup_snp1101', 'snp1101']

r_module: "r/r-4.0.0-gcc-10.1.0"

mpi_module: "openmpi/openmpi-3.1.3-intel-16.0.2"

snp1101_path: "/storage/hpc/group/UMAG/SCRIPTS/snp1101/snp1101"

geno_prefix: "data/raw_data/geno_dump/200924_HairShed.850K"

model: ['fixed9', 'an1', 'bg1', 'hfd1', 'igs1']

# BLUPF90 directories associated with each model
dir: {'fixed9':['data/derived_data/aireml_varcomp/fixed9'], 'hfd1':['data/derived_data/aireml_varcomp/hfd1'], 'an1':['data/derived_data/aireml_varcomp/an1'], 'bg1':['data/derived_data/aireml_varcomp/bg1'], 'igs1':['data/derived_data/aireml_varcomp/igs1'], 'fixed15':['data/derived_data/aireml_varcomp/fixed15'],
'length1':['data/derived_data/random_regression/length1']}

# BLUPF90 assigned animal effects associated with each model
animal_effect: {'fixed9':['2'], 'hfd1':['2'], 'an1':['2'], 'bg1':['2'], 'igs1':['2'], 'fixed15':['4']}

# BLUPF90 calculated variances associated with each model
gen_var: {'fixed9':['0.33133'], 'hfd1':['0.21463'], 'an1':['0.35806'], 'bg1':['0.26718'], 'igs1':['0.39053'], 'fixed15':['0.32491']}

# BLUPF90 calculated heritabilities associated with each model
h2: {'fixed9':['0.3675115'], 'hfd1':['0.320991'], 'an1':['0.3700003'], 'bg1':['0.3988189'], 'igs1':['0.4072084'], 'fixed15':['0.3628175']}
